/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;


import javax.swing.JDesktopPane;
import main.OpenGIS_MAIN;
import main.PressedButtonEnum;
import utility.ToolbarUtil;

/**
 *
 * @author Nushrat
 */
public class EditShapefile extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZoomPanel
     */
    OpenGIS_MAIN MAIN = null;
    JDesktopPane desk = null;

    public EditShapefile(final OpenGIS_MAIN MAIN, JDesktopPane desk) {
        super("", false, false, false, false);
        this.MAIN = MAIN;
        this.desk = desk;
        initComponents();
    }

    public EditShapefile(OpenGIS_MAIN MAIN) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditObject = new javax.swing.JButton();
        ObjectSelection = new javax.swing.JButton();
        DrawConnectionTest = new javax.swing.JButton();

        setTitle("Object Edit");
        setMaximumSize(new java.awt.Dimension(96, 69));
        setMinimumSize(new java.awt.Dimension(96, 69));
        setPreferredSize(new java.awt.Dimension(136, 69));

        EditObject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/EditIcon.png"))); // NOI18N
        EditObject.setToolTipText("Edit Object");
        EditObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditObjectActionPerformed(evt);
            }
        });

        ObjectSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/select.png"))); // NOI18N
        ObjectSelection.setToolTipText("Object Select");
        ObjectSelection.setActionCommand("jButtonRadar");
        ObjectSelection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ObjectSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectSelectionActionPerformed(evt);
            }
        });

        DrawConnectionTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DrawConnection.png"))); // NOI18N
        DrawConnectionTest.setToolTipText("Draw Connection");
        DrawConnectionTest.setActionCommand("jButtonRadar");
        DrawConnectionTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DrawConnectionTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawConnectionTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EditObject, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ObjectSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DrawConnectionTest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditObject, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ObjectSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(DrawConnectionTest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditObjectActionPerformed
        if (ToolbarUtil.getLastClickedComponent() != null) {
            ToolbarUtil.getLastClickedComponent().setBorder(null);
        }
        this.EditObject.setBorder(ToolbarUtil.getSelectedBorder());
        ToolbarUtil.setLastClickedComponent(this.EditObject);
        MAIN.lastPressedButton = PressedButtonEnum.EDIT_SHAPFILE;
    }//GEN-LAST:event_EditObjectActionPerformed

    private void ObjectSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectSelectionActionPerformed
        if (ToolbarUtil.getLastClickedComponent() != null) {
            ToolbarUtil.getLastClickedComponent().setBorder(null);
        }
        this.ObjectSelection.setBorder(ToolbarUtil.getSelectedBorder());
        ToolbarUtil.setLastClickedComponent(this.ObjectSelection);
        MAIN.lastPressedButton = PressedButtonEnum.SELECT_OBJECT;
    }//GEN-LAST:event_ObjectSelectionActionPerformed

    private void DrawConnectionTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawConnectionTestActionPerformed
        if (ToolbarUtil.getLastClickedComponent() != null) {
            ToolbarUtil.getLastClickedComponent().setBorder(null);
        }
        this.DrawConnectionTest.setBorder(ToolbarUtil.getSelectedBorder());
        ToolbarUtil.setLastClickedComponent(this.DrawConnectionTest);
        MAIN.lastPressedButton = PressedButtonEnum.DRAW_CONNECTION_TEST;
    }//GEN-LAST:event_DrawConnectionTestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DrawConnectionTest;
    private javax.swing.JButton EditObject;
    private javax.swing.JButton ObjectSelection;
    // End of variables declaration//GEN-END:variables
}
